export const FETCH_ALL_BLOG_POSTS = "FETCH_ALL_BLOG_POSTS"

export const ADD_NEW_BLOG_POSTS = "ADD_NEW_BLOG_POSTS"

export const FETCH_ONE_BLOG_POST = "FETCH_ONE_BLOG_POST"

export const PAGE_NOT_FOUND = "PAGE_NOT_FOUND"